### ISSUE TITLE
Make cloudsigma API URL configurable again

### ISSUE THREAD

**Issue by mjtrangoni** [cloudsigma/cloudsigma-sdk-go#14]
# Feature Request

### What is the problem that this feature solves?
Trying to update the sdk module to the latest version on [terraform-provider-cloudsigma](https://github.com/cloudsigma/terraform-provider-cloudsigma), I've found that the API URL is not configurable anymore. See [here](https://github.com/cloudsigma/cloudsigma-sdk-go/blob/8d591c660a432e826a02a50cb79b3f262c1831cb/cloudsigma/client.go#L23). This makes at least for me impossible to use the latest version, as in the terraform provider the URL was always configurable.

Are you planning to change this either here making the URL configurable again or removing the URL configuration on terraform side?

**Comment by pavel-github** [comment]
@mjtrangoni, URL configuration can be done [via Location](https://github.com/cloudsigma/cloudsigma-sdk-go/blob/3ddb23903c9b579ea63ce7f3dc79fd73433e088f/cloudsigma/client.go#L110) and opts pattern.
It's documented too: https://github.com/cloudsigma/cloudsigma-sdk-go/tree/3ddb23903c9b579ea63ce7f3dc79fd73433e088f?tab=readme-ov-file#authentication

Speaking about Terraform provider: updating SDK was done with this PR: https://github.com/cloudsigma/terraform-provider-cloudsigma/pull/67
